name: Angular Deploy to EC2 via CodeDeploy

on:
  push:
    branches:
      - main  # or 'master' or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🧱 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build Angular app
        run: npm run build -- --configuration production

      - name: 🛠 Make scripts executable
        run: chmod +x scripts/*.sh

      - name: 📁 Create deployment package
        run: |
          mkdir -p deploy
          cp -r dist/your-app deploy/dist
          cp -r scripts deploy/
          cp appspec.yml deploy/
          cd deploy
          zip -r angular-app.zip .

      - name: ☁️ Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks
        env:
          AWS_S3_BUCKET: your-s3-bucket-name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: your-region
          SOURCE_DIR: deploy
          DEST_DIR: /  # root of the bucket

      - name: 🚀 Deploy to CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: your-codedeploy-app
          deployment-group: your-codedeploy-group
          bundle-location: angular-app.zip
          bucket: your-s3-bucket-name
          region: your-region
          wait-until-completed: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
